### PR TITLE
fix animition spell

### PR DESCRIPTION
**Pull request by hefangshi**
change Animtion to Animation

### CODE REVIEW

**Comment by mdsb100** [comment]
```
 - WARN  | [YTXAnimations/AnimateCSS] xcodebuild:  /Users/travis/build/baidao/YTXAnimations/Pod/Classes/UIView+YTXAnimateCSS.m:12:17: warning: method definition for 'ytx_pluseAnimationWithDurationTime:' not found [-Wincomplete-implementation]
    - NOTE  | [YTXAnimations/AnimateCSS] xcodebuild:  /Users/travis/build/baidao/YTXAnimations/Pod/Classes/UIView+YTXAnimateCSS.h:16:1: note: method 'ytx_pluseAnimationWithDurationTime:' declared here
```

Please check it.

**Comment by hefangshi** [comment]
My fault, I only changed pluse in my own source code. Now the CI is green.

**Comment by mdsb100** [comment]
@hefangshi release 1.3.0. please `pod repo update`

**Comment by javenwang** [comment]
is that ok? you guys changed the public API.

**Comment by mdsb100** [comment]
No OK. But I do not wanna update version to 2.0

**Comment by hefangshi** [comment]
I think these spell mistake should fixed asap to reduce further impact.

**Pull request merged**
